version: '2'
volumes:
   netrics-etc:
   netrics-data:
services:
   netrics:
      container_name: netrics-anon-v0
      build:
        context: ./netrics/
        dockerfile: Dockerfile.template
      volumes:
         - 'netrics-etc:/etc/nm-exp-active-netrics/'
         - 'netrics-data:/var/nm/'
      privileged: true
      network_mode: host
   collect:
      container_name: collect-anon-v0
      build: 
        context: ./collect/
        dockerfile: Dockerfile.template
      volumes:
         - 'netrics-etc:/etc/nm-exp-active-netrics/'
         - 'netrics-data:/var/nm/'
      environment:
         - BALENA_DEVICE_UUID=df0d94716857f9d9e85d74027673bd1d
         - NETRICS_ACTIVATION_DATE=20220920
         #- NETRICS_ID=nm-anon-20220920-00000000
      privileged: true
      network_mode: host
